# Generated by Django 2.2 on 2019-12-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='nickname',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
