# Generated by Django 2.2 on 2019-12-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_password_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='password',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='event',
            name='url_key',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
