# Generated by Django 2.2 on 2019-12-28 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191227_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['likes', 'uploaded_at']},
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
