# Generated by Django 2.2 on 2019-12-29 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191228_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-likes', 'uploaded_at']},
        ),
    ]
