# Generated by Django 2.2 on 2020-01-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200102_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
